version: "2"
services:
  consul1:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"
  consul2:
    image: "progrium/consul:latest"
    container_name: "consul2"
    hostname: "consul2"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul1"
    depends_on:
      - consul1
  consul3:
    image: "progrium/consul:latest"
    container_name: "consul3"
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul1"
    depends_on:
      - consul1
  registrator:
    image: "gliderlabs/registrator"
    hostname: "registrator"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul1
    command: -internal consul://consul1:8500
  sample_service:
    image: "thangchung/sample_service"
    build:
      context: .
      dockerfile: Dockerfile.SampleService 
    hostname: sample_service
    ports:
      - "6000:6000"
    environment:
      SERVICE_NAME: sample_service
      SERVICE_TAGS: magazine
    dns: 192.168.99.100
    dns_search: service.consul
networks:
  default:
    external:
      name: my-net